### ISSUE TITLE
Static resource links are not working

### ISSUE THREAD

**Issue by Yosi85** [pikax/swgoh#10]
So far I've been using your lbirary by setting the img src attributes to the link that is provided for the toons. For example: https://swgoh.gg/static/img/assets/tex.charui_wampa.png
This link works in the browser but it doesn't work in the application.
I get the following error:
![swgoh - issue](https://user-images.githubusercontent.com/4134160/40266078-14532aac-5b45-11e8-8ba8-9d515887078f.png)
Is there a workaround for this issue? Or alternatively could you pack the static resources (images) to the library so we can reference them locally?

Thanks! And keep up the good work!

Best Regards,
 Robert

**Comment by pikax** [comment]
The problem is with the browser, because you are setting the image source directly from swgoh.gg, and it seems it blocks when the *referer* is not swgoh domain.

I can't include the images in the package, because it will grow the package size.

But I can provide the images from this github repository.

Other solutions would be proxying the images through a service or you store them in a folder and provide them.

If you need a quick workaround you should download or proxy them, because I can only implement it next weekend.

Thank you
